### ISSUE TITLE
It is recommended to use tag as the name of the folder by default

### ISSUE THREAD

**Issue by dislazy** [sn-extensions/github-push#15]
It is recommended to use tag as the default name of the folder, so as to better save the file to gituhub，thanks

**Comment by JaspalSuri** [comment]
Hi @dislazy, can you share a screenshot of what you're referring to? I think simply naming a file or repo something that you can remember is a good start.

**Comment by dislazy** [comment]
Just like this, the tag of the current note can be filled in the directory by default

<img width="848" alt="WX20210727-110117@2x" src="https://user-images.githubusercontent.com/30426054/127088515-23ef966e-88ea-4a7b-878b-e041bea8dfe4.png">

**Comment by JaspalSuri** [comment]
Hi @dislazy, thank you for elaborating! We will probably keep things as is to avoid disrupting the workflows of other users of this extension who might not want this feature.

**Comment by dislazy** [comment]
> Hi @dislazy, thank you for elaborating! We will probably keep things as is to avoid disrupting the workflows of other users of this extension who might not want this feature.

Well, it’s a pity, but I think it’s more user-friendly to organize data if there is a folder concept
