### ISSUE TITLE
Error when trying to push

### ISSUE THREAD

**Issue by kenmcewan** [sn-extensions/github-push#2]
When trying to Push any note getting the following error:

![Screenshot 2020-02-14 at 10 47 34](https://user-images.githubusercontent.com/5707644/74497088-a1771700-4f17-11ea-88f3-658712e432f5.png)

The github token seems okay as the repository list is being populated okay - although only with public one's, is that correct ?

Latest version 3.3.2 but was also happening on 3.3.1.
Thanks

**Comment by atmoio** [comment]
Hmm not sure. I'd try checking to see if your token has proper read+write privileges.

**Comment by kenmcewan** [comment]
thanks, yes changing the permissions worked!

**Comment by ryanpcmcquen** [comment]
What are the correct privileges?

**Comment by JaspalSuri** [comment]
What privileges have you enabled so far?

**Comment by ryanpcmcquen** [comment]
None, I was hoping it was documented somewhere ...

**Comment by JaspalSuri** [comment]
I see - I've assigned someone to look into it so that way we can provide you with accurate information; this way you won't have to worry about enabling something that is not needed.

**Comment by JaspalSuri** [comment]
![image](https://user-images.githubusercontent.com/44656000/92872381-cef74680-f3ba-11ea-9b2a-e0b56f8919a3.png)

Hello again @ryanpcmcquen,

You should be able to read and write to your public repos with just this scope. 

Please let me know if you have any other questions!
